@extends($activeTemplate . 'layouts.frontend')
@section('content')
<div class="loan-application-wrapper"><div class="container section">
<div class="loan-app-header text-center mb-5"><h2 class="loan-app-title">@lang('Selling Mortgage Application')</h2><p class="loan-app-subtitle">@lang('Step 2 of 4: Business Information')</p></div>
<div class="loan-steps-wrapper mb-5"><div class="loan-steps">
<div class="loan-step completed"><div class="loan-step-icon"><i class="las la-check"></i></div><div class="loan-step-content"><span class="loan-step-number">01</span><span class="loan-step-title">@lang('Personal')</span></div></div><div class="loan-step-line completed"></div>
<div class="loan-step active"><div class="loan-step-icon"><i class="las la-briefcase"></i></div><div class="loan-step-content"><span class="loan-step-number">02</span><span class="loan-step-title">@lang('Business')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-home"></i></div><div class="loan-step-content"><span class="loan-step-number">03</span><span class="loan-step-title">@lang('Mortgage')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-file-pdf"></i></div><div class="loan-step-content"><span class="loan-step-number">04</span><span class="loan-step-title">@lang('Documents')</span></div></div>
</div></div>
<form method="POST" action="{{ route('selling.mortgage.step2.store') }}" id="sellingMortgageStep2" class="loan-wizard-form">@csrf
<div class="loan-form-card"><div class="loan-form-card-header"><div class="loan-form-card-icon"><i class="las la-briefcase"></i></div><div><h4 class="loan-form-card-title">@lang('Business Information')</h4><p class="loan-form-card-subtitle">@lang('Your business details')</p></div></div>
<div class="loan-form-card-body"><div class="row g-4">
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-building label-icon"></i>@lang('Business Name')</label><input type="text" name="business_name" class="loan-form-control" value="{{ old('business_name', session('selling_mortgage.business_name')) }}" placeholder="@lang('Company name')"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-file-invoice label-icon"></i>@lang('VAT Number')</label><input type="text" name="vat_number" class="loan-form-control" value="{{ old('vat_number', session('selling_mortgage.vat_number')) }}" placeholder="IT12345678901"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-store label-icon"></i>@lang('Business Type')</label><div class="custom--nice-select"><select name="business_type" id="business_type"><option value="" disabled selected>@lang('Select')</option><option value="sole_proprietor" {{ old('business_type', session('selling_mortgage.business_type')) == 'sole_proprietor' ? 'selected' : '' }}>@lang('Sole Proprietor')</option><option value="partnership" {{ old('business_type', session('selling_mortgage.business_type')) == 'partnership' ? 'selected' : '' }}>@lang('Partnership')</option><option value="corporation" {{ old('business_type', session('selling_mortgage.business_type')) == 'corporation' ? 'selected' : '' }}>@lang('Corporation')</option><option value="other" {{ old('business_type', session('selling_mortgage.business_type')) == 'other' ? 'selected' : '' }}>@lang('Other')</option></select></div><span class="error-message" id="business_type_error"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-clock label-icon"></i>@lang('Business Years')</label><input type="number" name="business_years" class="loan-form-control" value="{{ old('business_years', session('selling_mortgage.business_years')) }}" placeholder="5"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-chart-line label-icon"></i>@lang('Annual Revenue (€)')</label><div class="input-with-icon"><span class="input-icon-left">€</span><input type="number" step="0.01" name="annual_revenue" class="loan-form-control with-icon" value="{{ old('annual_revenue', session('selling_mortgage.annual_revenue')) }}" placeholder="100,000"></div><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-euro-sign label-icon"></i>@lang('Monthly Net Income (€)')</label><div class="input-with-icon"><span class="input-icon-left">€</span><input type="number" step="0.01" name="monthly_net_income" class="loan-form-control with-icon" value="{{ old('monthly_net_income', session('selling_mortgage.monthly_net_income')) }}" placeholder="5,000"></div><span class="error-message"></span></div></div>
</div></div></div>
<div class="loan-form-actions"><a href="{{ route('selling.mortgage.wizard') }}" class="loan-back-btn"><i class="las la-arrow-left"></i>@lang('Back')</a><button type="submit" class="loan-submit-btn"><span class="btn-text">@lang('Next: Mortgage')</span><i class="las la-arrow-right btn-icon"></i></button></div>
</form></div></div>
@endsection
@include('Template::frontend.personal_loan.styles')
@include('Template::frontend.employee_loan.validation_script')
