@extends($activeTemplate . 'layouts.frontend')
@section('content')
<div class="loan-application-wrapper">
<div class="container section">
<div class="loan-app-header text-center mb-5"><h2 class="loan-app-title">@lang('Selling Mortgage Application')</h2><p class="loan-app-subtitle">@lang('Step 1 of 4: Personal Information')</p></div>
<div class="loan-steps-wrapper mb-5"><div class="loan-steps">
<div class="loan-step active"><div class="loan-step-icon"><i class="las la-user"></i></div><div class="loan-step-content"><span class="loan-step-number">01</span><span class="loan-step-title">@lang('Personal')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-briefcase"></i></div><div class="loan-step-content"><span class="loan-step-number">02</span><span class="loan-step-title">@lang('Business')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-home"></i></div><div class="loan-step-content"><span class="loan-step-number">03</span><span class="loan-step-title">@lang('Mortgage')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-file-pdf"></i></div><div class="loan-step-content"><span class="loan-step-number">04</span><span class="loan-step-title">@lang('Documents')</span></div></div>
</div></div>
<form method="POST" action="{{ route('selling.mortgage.step1.store') }}" id="sellingMortgageStep1" class="loan-wizard-form">@csrf
<div class="loan-form-card"><div class="loan-form-card-header"><div class="loan-form-card-icon"><i class="las la-user-circle"></i></div><div><h4 class="loan-form-card-title">@lang('Personal Information')</h4><p class="loan-form-card-subtitle">@lang('Your personal details')</p></div></div>
<div class="loan-form-card-body"><div class="row g-4">
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-user label-icon"></i>@lang('First Name')</label><input type="text" name="first_name" class="loan-form-control" value="{{ old('first_name', session('selling_mortgage.first_name', $user->firstname ?? '')) }}" placeholder="@lang('First name')"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-user label-icon"></i>@lang('Last Name')</label><input type="text" name="last_name" class="loan-form-control" value="{{ old('last_name', session('selling_mortgage.last_name', $user->lastname ?? '')) }}" placeholder="@lang('Last name')"><span class="error-message"></span></div></div>
<div class="col-md-4"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-calendar label-icon"></i>@lang('Date of Birth')</label><input type="date" name="date_of_birth" class="loan-form-control" value="{{ old('date_of_birth', session('selling_mortgage.date_of_birth', '')) }}"><span class="error-message"></span></div></div>
<div class="col-md-4"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-sort-numeric-up label-icon"></i>@lang('Age')</label><input type="number" name="age" class="loan-form-control" value="{{ old('age', session('selling_mortgage.age', '')) }}" placeholder="35"><span class="error-message"></span></div></div>
<div class="col-md-4"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-id-card label-icon"></i>@lang('Tax Code')</label><input type="text" name="tax_code" class="loan-form-control" value="{{ old('tax_code', session('selling_mortgage.tax_code', '')) }}" placeholder="@lang('Tax code')"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-envelope label-icon"></i>@lang('Email')</label><input type="email" name="email" class="loan-form-control" value="{{ old('email', session('selling_mortgage.email', $user->email ?? '')) }}" placeholder="@lang('email@example.com')"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-phone label-icon"></i>@lang('Mobile')</label><input type="text" name="mobile" class="loan-form-control" value="{{ old('mobile', session('selling_mortgage.mobile', $user->mobile ?? '')) }}" placeholder="+39 333 0000000"><span class="error-message"></span></div></div>
<div class="col-md-8"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-map-marker label-icon"></i>@lang('City')</label><input type="text" name="city" class="loan-form-control" value="{{ old('city', session('selling_mortgage.city', $user->city ?? '')) }}" placeholder="Milan"><span class="error-message"></span></div></div>
<div class="col-md-4"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-map label-icon"></i>@lang('Province')</label><input type="text" name="province" class="loan-form-control" value="{{ old('province', session('selling_mortgage.province', $user->state ?? '')) }}" placeholder="MI" maxlength="2"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-heart label-icon"></i>@lang('Marital Status')</label><div class="custom--nice-select"><select name="marital_status" id="marital_status"><option value="" disabled selected>@lang('Select')</option><option value="married" {{ old('marital_status', session('selling_mortgage.marital_status')) == 'married' ? 'selected' : '' }}>@lang('Married')</option><option value="single" {{ old('marital_status', session('selling_mortgage.marital_status')) == 'single' ? 'selected' : '' }}>@lang('Single')</option><option value="cohabiting" {{ old('marital_status', session('selling_mortgage.marital_status')) == 'cohabiting' ? 'selected' : '' }}>@lang('Cohabiting')</option></select></div><span class="error-message" id="marital_status_error"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-users label-icon"></i>@lang('Family Status')</label><input type="text" name="family_status" class="loan-form-control" value="{{ old('family_status', session('selling_mortgage.family_status')) }}" placeholder="@lang('e.g., Married with children')"><span class="error-message"></span></div></div>
<div class="col-md-12"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-home label-icon"></i>@lang('Family Members')</label><input type="number" name="family_members" class="loan-form-control" value="{{ old('family_members', session('selling_mortgage.family_members')) }}" placeholder="3"><span class="error-message"></span></div></div>
</div></div></div>
<div class="loan-form-actions"><a href="{{ route('loan.type.selector') }}" class="loan-back-btn"><i class="las la-arrow-left"></i>@lang('Back')</a><button type="submit" class="loan-submit-btn"><span class="btn-text">@lang('Next: Business')</span><i class="las la-arrow-right btn-icon"></i></button></div>
</form></div></div>
@endsection
@include('Template::frontend.personal_loan.styles')
@include('Template::frontend.employee_loan.validation_script')


