@extends($activeTemplate . 'layouts.frontend')
@section('content')
<div class="loan-application-wrapper"><div class="container section">
<div class="loan-app-header text-center mb-5"><h2 class="loan-app-title">@lang('Selling Mortgage Application')</h2><p class="loan-app-subtitle">@lang('Step 3 of 4: Mortgage Details')</p></div>
<div class="loan-steps-wrapper mb-5"><div class="loan-steps">
<div class="loan-step completed"><div class="loan-step-icon"><i class="las la-check"></i></div><div class="loan-step-content"><span class="loan-step-number">01</span><span class="loan-step-title">@lang('Personal')</span></div></div><div class="loan-step-line completed"></div>
<div class="loan-step completed"><div class="loan-step-icon"><i class="las la-check"></i></div><div class="loan-step-content"><span class="loan-step-number">02</span><span class="loan-step-title">@lang('Business')</span></div></div><div class="loan-step-line completed"></div>
<div class="loan-step active"><div class="loan-step-icon"><i class="las la-home"></i></div><div class="loan-step-content"><span class="loan-step-number">03</span><span class="loan-step-title">@lang('Mortgage')</span></div></div><div class="loan-step-line"></div>
<div class="loan-step"><div class="loan-step-icon"><i class="las la-file-pdf"></i></div><div class="loan-step-content"><span class="loan-step-number">04</span><span class="loan-step-title">@lang('Documents')</span></div></div>
</div></div>
<form method="POST" action="{{ route('selling.mortgage.step3.store') }}" id="sellingMortgageStep3" class="loan-wizard-form">@csrf
<div class="loan-form-card"><div class="loan-form-card-header"><div class="loan-form-card-icon"><i class="las la-home"></i></div><div><h4 class="loan-form-card-title">@lang('Mortgage Details')</h4><p class="loan-form-card-subtitle">@lang('Property and mortgage information')</p></div></div>
<div class="loan-form-card-body"><div class="row g-4">
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-euro-sign label-icon"></i>@lang('Mortgage Amount (€)')</label><div class="input-with-icon"><span class="input-icon-left">€</span><input type="number" step="0.01" name="mortgage_amount" class="loan-form-control with-icon" value="{{ old('mortgage_amount', session('selling_mortgage.mortgage_amount')) }}" placeholder="200,000"><span class="error-message"></span></div></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-calendar-alt label-icon"></i>@lang('Duration (months)')</label><input type="number" name="mortgage_duration_months" class="loan-form-control" value="{{ old('mortgage_duration_months', session('selling_mortgage.mortgage_duration_months')) }}" placeholder="240"><span class="error-message"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-building label-icon"></i>@lang('Property Type')</label><div class="custom--nice-select"><select name="property_type" id="property_type"><option value="" disabled selected>@lang('Select')</option><option value="residential" {{ old('property_type', session('selling_mortgage.property_type')) == 'residential' ? 'selected' : '' }}>@lang('Residential')</option><option value="commercial" {{ old('property_type', session('selling_mortgage.property_type')) == 'commercial' ? 'selected' : '' }}>@lang('Commercial')</option><option value="mixed" {{ old('property_type', session('selling_mortgage.property_type')) == 'mixed' ? 'selected' : '' }}>@lang('Mixed Use')</option></select></div><span class="error-message" id="property_type_error"></span></div></div>
<div class="col-md-6"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-map-marked label-icon"></i>@lang('Property Location')</label><input type="text" name="property_location" class="loan-form-control" value="{{ old('property_location', session('selling_mortgage.property_location')) }}" placeholder="@lang('Address')"><span class="error-message"></span></div></div>
<div class="col-md-12"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-clipboard label-icon"></i>@lang('Mortgage Purpose')</label><textarea name="mortgage_purpose" class="loan-form-textarea" rows="3" placeholder="@lang('Describe the purpose')">{{ old('mortgage_purpose', session('selling_mortgage.mortgage_purpose')) }}</textarea><span class="error-message"></span></div></div>
<div class="col-md-12"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-list label-icon"></i>@lang('Current Financing')</label><textarea name="current_financing_details" class="loan-form-textarea" rows="2" placeholder="@lang('Any existing loans')">{{ old('current_financing_details', session('selling_mortgage.current_financing_details')) }}</textarea><span class="error-message"></span></div></div>
<div class="col-md-12"><div class="loan-form-group"><label class="loan-form-label"><i class="las la-money-bill-wave label-icon"></i>@lang('Remaining Amount (€)')</label><div class="input-with-icon"><span class="input-icon-left">€</span><input type="number" step="0.01" name="current_financing_remaining" class="loan-form-control with-icon" value="{{ old('current_financing_remaining', session('selling_mortgage.current_financing_remaining')) }}" placeholder="0"><span class="error-message"></span></div></div></div>
</div></div></div>
<div class="loan-form-actions"><a href="{{ route('selling.mortgage.step2') }}" class="loan-back-btn"><i class="las la-arrow-left"></i>@lang('Back')</a><button type="submit" class="loan-submit-btn"><span class="btn-text">@lang('Next: Documents')</span><i class="las la-arrow-right btn-icon"></i></button></div>
</form></div></div>
@endsection
@include('Template::frontend.personal_loan.styles')
@include('Template::frontend.employee_loan.validation_script')


